az group update --name "rg-catos-dev-04" --tags "Approved by"="Tejinder" "Dept"="IT"
az group update --name "n01-cc-rg-cldops-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "NetworkWatcherRG" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "vm-it-connect365-cc-01_group" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "AzureBackupRG_canadacentral_1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-logicapps-it-cc-uat-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Project"="Azure Landing Zone"
az group update --name "rg-logicapps-it-cc-prod-1" --tags "Approved by"="Tejinder" "Requested by"="Monty"
az group update --name "rg-returns-uat-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-returns-dev-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-returns-qa-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-catos-qa-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-cim-d-cc-03" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-cim-uat-cc-02" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-catos-qa-02" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-connect365-stg-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-connect365" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-paybybank-dev-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-odrbiclrsql-test" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "CyberJusticeDev" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "LogAnalyticsDefaultResources" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "n01-cc-rg-crm-managedidentity-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Project"="Azure Landing Zone"
az group update --name "CAT-ODR-UAT" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-cc-cao-cmrao-datashare" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "ai_appi-catodr-log-test_9f99173d-6b2a-4b79-819b-9d57961b61a5_managed" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "DefaultResourceGroup-CCAN" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-automation-np-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-catodr-dev-wks-001" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-it-cc-test-amir-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-catos-shared-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-it-sentinel-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "rg-returns-shared-01" --tags "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-catosdw-dev-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-returns-staging-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-cim-stage-cc-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-catos-stage-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "n01-cc-rg-vm-ali" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "n01-cc-rg-vm-vmcatodrdevwks001" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-catodr-cache-1" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-backup-vms-dev-01" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT" "Project"="Azure Landing Zone"
az group update --name "CAO_BI" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
az group update --name "rg-cmrao-cao-datatransfer" --tags "Approved by"="Tejinder" "Requested by"="Monty" "Dept"="IT"
